!!com.snobot.simulator.config.v1.SimulatorConfigV1
mAccelerometers: []
mAnalogIn: []
mAnalogOut: []
mDefaultI2CWrappers: {}
mDefaultSpiWrappers: {}
mDigitalIO:
- mHandle: 0
  mName: Digital IO 0
  mType: com.snobot.simulator.module_wrapper.wpi.WpiDigitalIoWrapper
- mHandle: 1
  mName: Digital IO 1
  mType: com.snobot.simulator.module_wrapper.wpi.WpiDigitalIoWrapper
mEncoders:
- mConnectedSpeedControllerHandle: -1
  mHandle: 0
  mName: Encoder 0
  mType: com.snobot.simulator.module_wrapper.wpi.WpiEncoderWrapper
mGyros: []
mPwm:
- mHandle: 0
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: motorRF
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 1
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: motorRB
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 2
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: motorLF
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 3
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: motorLB
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 4
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: motorLift
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 5
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: motorGrabLeft
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 6
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: motorGrabRight
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 7
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: motorClimb
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
mRelays: []
mSimulatorComponents: []
mSolenoids: []
